# Services
services:

  # DDC Service
  radio-app:
    container_name: radio-app
    image: opeoniye/nginx-php-fpm
    # environment:
    #   GIT_REPO: ${GIT_REPO}
    #   GIT_EMAIL: ${GIT_EMAIL}
    #   GIT_NAME: ${GIT_NAME}
    #   GIT_BRANCH: ${GIT_BRANCH}
    #   GIT_PERSONAL_TOKEN: ${GIT_PERSONAL_TOKEN}
    #   WEBROOT: ${WEBROOT}
    ports:
      - 1004:80
    networks:
      - bams
    volumes:
      - ./:/var/www/html
      - ./.docker/radio.conf:/etc/nginx/sites-available/default.conf
      # - ./.env:/var/www/html/.env
    restart: always

networks:
  bams:
    name: bams-dev
    external: true 