<?php
return [
    '' => [
        'label'        => 'English/Anglais',
        'title'        => 'DCLM Radio :: Achieving Heaven\'s Goal',
        'display_name' => 'DCLM Online Radio',
        'artist'       => 'DCLM Radio',
        'stream_url'   => 'https://airtime.dclm.org/radio/8000/live',
        'api_id'       => 1,
    ],
    'french' => [
        'label'        => 'French/Français',
        'title'        => 'French/Français :: DCLM Radio',
        'display_name' => 'DCLM Radio - French/Français',
        'artist'       => 'DCLM Radio',
        'stream_url'   => 'https://airtime.dclm.org/radio/8050/french',
        'api_id'       => 3,
    ],
    'spanish' => [
        'label'        => 'Spanish/Español',
        'title'        => 'Spanish/Español :: DCLM Radio',
        'display_name' => 'DCLM Radio - Spanish/Español',
        'artist'       => 'DCLM Radio - Spanish',
        'stream_url'   => 'https://airtime.dclm.org/radio/8100/spanish',
        'api_id'       => 8,
    ],
    'portuguese' => [
        'label'        => 'Portuguese/Portugais',
        'title'        => 'Portuguese :: DCLM Radio',
        'display_name' => 'DCLM Radio - Portuguese',
        'artist'       => 'DCLM Radio - Portuguese',
        'stream_url'   => 'https://airtime.dclm.org/radio/8110/portuguese',
        'api_id'       => 6,
    ],
    'egun' => [
        'label'        => 'Gungbe/Egun',
        'title'        => 'Gungbe/Egun :: DCLM Radio',
        'display_name' => 'DCLM Radio - Gungbe/Egun',
        'artist'       => 'DCLM Radio',
        'stream_url'   => 'https://airtime.dclm.org/radio/8120/egun',
        'api_id'       => 7,
    ],
    'yoruba' => [
        'label'        => 'Yoruba',
        'title'        => 'Yoruba :: DCLM Radio',
        'display_name' => 'DCLM Radio - Yoruba',
        'artist'       => 'DCLM Radio - Yoruba',
        'stream_url'   => 'https://airtime.dclm.org/radio/8060/yoruba',
        'api_id'       => 2,
    ],
    'hausa' => [
        'label'        => 'Hausa',
        'title'        => 'Hausa :: DCLM Radio',
        'display_name' => 'DCLM Radio - Hausa',
        'artist'       => 'DCLM Radio - Hausa',
        'stream_url'   => 'https://airtime.dclm.org/radio/8070/hausa',
        'api_id'       => 4,
    ],
    'igbo' => [
        'label'        => 'Igbo',
        'title'        => 'Igbo :: DCLM Radio',
        'display_name' => 'DCLM Radio - Igbo',
        'artist'       => 'DCLM Radio - Igbo',
        'stream_url'   => 'https://airtime.dclm.org/radio/8090/igbo',
        'api_id'       => 5,
    ],
    'ebira' => [
        'label'        => 'Ebira',
        'title'        => 'Ebira :: DCLM Radio',
        'display_name' => 'DCLM Radio - Ebira',
        'artist'       => 'DCLM Radio - Ebira',
        'stream_url'   => 'https://airtime.dclm.org/radio/8125/ebira',
        'api_id'       => 9,
    ],
    'efik' => [
        'label'        => 'Efik',
        'title'        => 'Efik :: DCLM Radio',
        'display_name' => 'DCLM Radio - Efik',
        'artist'       => 'DCLM Radio - Efik',
        'stream_url'   => 'https://airtime.dclm.org/radio/8145/efik',
        'api_id'       => 10,
    ],
    'ewe' => [
        'label'        => 'Ewe',
        'title'        => 'Ewe :: DCLM Radio',
        'display_name' => 'DCLM Radio - Ewe',
        'artist'       => 'DCLM Radio - Ewe',
        'stream_url'   => 'https://airtime.dclm.org/radio/8140/ewe',
        'api_id'       => 11,
    ],
    'twi' => [
        'label'        => 'Twi',
        'title'        => 'Twi :: DCLM Radio',
        'display_name' => 'DCLM Radio - Twi',
        'artist'       => 'DCLM Radio - Twi',
        'stream_url'   => 'https://airtime.dclm.org/radio/8135/twi',
        'api_id'       => 12,
    ],
    'urhobo' => [
        'label'        => 'Urhobo',
        'title'        => 'Urhobo :: DCLM Radio',
        'display_name' => 'DCLM Radio - Urhobo',
        'artist'       => 'DCLM Radio - Urhobo',
        'stream_url'   => 'https://studio.dclm.org/listen/urhobo/urhobo',
        'api_id'       => 13,
    ],
    'idoma' => [
        'label'        => 'Idoma',
        'title'        => 'Idoma :: DCLM Radio',
        'display_name' => 'DCLM Radio - Idoma',
        'artist'       => 'DCLM Radio - Idoma',
        'stream_url'   => 'https://airtime.dclm.org/radio/8220/idoma',
        'api_id'       => 15,
    ],
    'igede' => [
        'label'        => 'Igede',
        'title'        => 'Igede :: DCLM Radio',
        'display_name' => 'DCLM Radio - Igede',
        'artist'       => 'DCLM Radio - Igede',
        'stream_url'   => 'https://airtime.dclm.org/radio/8230/igede',
        'api_id'       => 14,
    ],
    'tiv' => [
        'label'        => 'Tiv',
        'title'        => 'Tiv :: DCLM Radio',
        'display_name' => 'DCLM Radio - Tiv',
        'artist'       => 'DCLM Radio - Tiv',
        'stream_url'   => 'https://airtime.dclm.org/radio/8240/tiv',
        'api_id'       => 16,
    ],
    'gbagyi' => [
        'label'        => 'Gbagyi',
        'title'        => 'Gbagyi :: DCLM Radio',
        'display_name' => 'DCLM Radio - Gbagyi',
        'artist'       => 'DCLM Radio - Gbagyi',
        'stream_url'   => 'https://airtime.dclm.org/radio/8250/gbagyi',
        'api_id'       => 16,
    ],
    'igala' => [
        'label'        => 'Igala',
        'title'        => 'Igala :: DCLM Radio',
        'display_name' => 'DCLM Radio - Igala',
        'artist'       => 'DCLM Radio - Igala',
        'stream_url'   => 'https://airtime.dclm.org/radio/8040/igala',
        'api_id'       => 18,
    ],
];
